name: 'Microfrontend Orchestrator Uploader'
description: 'Zip a folder and upload it to microfrontend orchestrator service'
author: 'Lorenzo De Francesco'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  apikey:
    description: 'API key for authentication into microfrontend orchestrator service'
    required: true
  microfrontend-slug:
    description: 'Slug of the microfrontend'
    required: true
  domain:
    description: 'Base domain of the microfrontend orchestrator service (e.g. https://console.mfe-orchestrator.dev)'
    required: false
    default: 'https://console.mfe-orchestrator.dev'
  file-path:
    description: 'Path to the folder to zip (default: dist)'
    required: false
    default: 'dist'
  version:
    description: 'Version to upload (default: github.ref_name)'
    required: false
    default: ${{ github.ref_name }}
outputs:
  status:
    description: 'The status of the upload operation'
runs:
  using: 'node20'
  main: 'dist/index.js'